spring.application.name=pagina web de juegos
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/JuegosMentales_BD
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=user
spring.security.user.password=admin321

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a83a7c001@smtp-brevo.com
spring.mail.password=PonerContraseñaAqui

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2